const AnuncioCenso = () => {



  return (
    <div className=" max-w-6xl px-4 sm:px-6 lg:px-8 mx-auto pt-6">
      <div className="mt-2 p-4 bg-yellow-50 border border-yellow-200 rounded-lg shadow  hover:scale-110">
        <p className="text-sm text-yellow-800 font-medium text-justify">
          ESTIMADOS VECINOS <br />
          <br />
          EL LUNES 23/02/26 <br /> <br/>
          DAREMOS INICIO A UN TRABAJO DE LIMPIEZA Y PROTECCIÓN DE LA LÁMINA INFERIOR COMPLETA DEL TANQUE GRANDE, ESTO PARA PROLONGAR LA VIDA ÚTIL DE DICHAS LÁMINAS QUE YA PRESENTAN SIGNOS PEQUEÑOS DE DETERIORO. <br /> <br/>
          PARA TAL LABOR SE DEBE TENER EL TANQUE COMPLETAMENTE VACÍO, YA QUE DICHAS LÁMINAS POR EL LADO INTERNO DEL TANQUE ESTÁN MAS PROFUNDAS QUE POR EL LADO EXTERNO. EL TRABAJO CONSTA DE
          CEPILLADO INTERNO PARA REMOVER LA CAPA DAÑADA, SELLADO DE PEQUEÑAS FISURAS,  RECUBRIMIENTO CON POLIURETANO (APTO PARA ALIMENTOS Y CONSUMO HUMANO) DE TODA EL ÁREA Y,
          PINTURA EXTERNA CON CROMATO DE ZINC DE TODAS LAS LÁMINAS PARA PROTECCIÓN Y MEJORAMIENTO DE LA DENSIDAD DE LAS LÁMINAS. <br /> <br/>

          LA DURACIÓN DE ESE TRABAJO SE ESTIMA EN ALREDEDOR DE 7 DÍAS, YA QUE HAY QUE CONSIDERAR LOS TIEMPOS DE VACIADO TOTAL DEL TANQUE Y SECADO DE LOS PRODUCTOS APLICADOS. <br /> <br/>

          ADEMÁS,  SE DEBE TOMAR EN CUENTA EL TIEMPO QUE TARDARÍA EL TANQUE EN LLENARSE PARA PODER SURTIR AGUA HACIA LOS TH ES POR ESO QUE SOLICITAMOS QUE TOMEN SUS PREVISIONES PERTINENTES YA QUE NO SE SURTIRÁ AGUA A LOS TH EN UN PERÍODO CONSIDERABLE DE TIEMPO. <br /> <br/>

          EL DOMINGO 22/02 SE VACIARÁ EL TANQUE PARA DICHO TRABAJO. <br /> <br/>

          MUCHAS GRACIAS
        </p>
      </div>
    </div>
  );
};

export default AnuncioCenso;